export const WEDDING = {
  bride: 'Ankita',
  groom: 'Amrit',
  brideFullName: 'Ankita',
  groomFullName: 'Amrit',
  hashtag: '#AnkitaWedsAmrit',
  beginningPhrase: '“These kids are getting married”',
  phoneRsvp: '+919876543210',
  date: new Date('2026-12-09T19:00:00+05:30'),
  dateLabel: 'Wednesday, 9 December 2026',
  timeLabel: '7:00 PM onwards',
  venue: 'Sahyadri Mangal Karyalay',
  venueShort: 'Sahyadri Mangal Karyalay',
  city: 'Maharashtra',
  mapQuery: 'Sahyadri Mangal Karyalay',
  mapsUrl: 'https://maps.app.goo.gl/V5mNtMtpdc1T8TFp6?g_st=ic',
  stayVenue: 'Swarg Sahyadri Farms',
  music: {
    title: 'Tum Prem Ho',
    artist: 'Radhe Krishna • Mohit Lalwani',
    youtubeUrl: 'https://music.youtube.com/watch?v=mCsoAPRI52U&si=HPXbwNaH2UmjEcfA',
    youtubeId: 'mCsoAPRI52U',
  },
  weather: {
    temp: '22°C / 72°F',
    condition: 'Pleasant & Crisp Winter Evening',
    forecast: 'Starlit celebrations with gentle evening breeze',
  },
  coupleBios: {
    amrit: {
      name: 'Amrit',
      role: 'The Groom',
      image: '/assets/childhood_amrit.jpg',
      lines: [
        'Never the loudest in the room, just the most curious.',
        'Spent years learning to build things that last.',
        'Turns out, that’s the same thing as learning to love.',
      ],
    },
    ankita: {
      name: 'Ankita',
      role: 'The Bride',
      image: '/assets/childhood_ankita.jpg',
      lines: [
        'Equal parts filmy, foodie and hopelessly romantic—with a little sarcasm sprinkled in.',
        'She believes the best stories are the ones you never planned.',
      ],
    },
    teaStory: {
      title: 'From Tea to Together',
      subtitle: 'Where it all began',
      description: 'Talking over tea one fine day, we began a beautiful journey together.',
      image: '/assets/event_sangeet.jpg',
    },
  },
  storySummary: 'Talking over tea one fine day, we began a beautiful journey together. Now, these two kids who grew up dreaming are getting married!',
  storyMilestones: [
    {
      year: 'The Groom',
      title: 'Amrit',
      subtitle: 'Never the loudest in the room, just the most curious',
      description: 'Spent years learning to build things that last. Turns out, that’s the same thing as learning to love.',
      icon: '🤠',
      image: '/assets/childhood_amrit.jpg',
    },
    {
      year: 'The Bride',
      title: 'Ankita',
      subtitle: 'Filmy, foodie & hopelessly romantic',
      description: 'Equal parts filmy, foodie and hopelessly romantic—with a little sarcasm sprinkled in. She believes the best stories are the ones you never planned.',
      icon: '🎀',
      image: '/assets/childhood_ankita.jpg',
    },
    {
      year: 'The Beginning',
      title: 'From Tea to Together',
      subtitle: 'A shared cup, a lifetime of memories',
      description: 'Talking over tea one fine day, we began a beautiful journey together.',
      icon: '☕',
      image: '/assets/event_sangeet.jpg',
    },
  ],
  events: [
    {
      id: 'mehendi',
      day: 'Day 1',
      title: 'Mehendi Ceremony',
      date: 'Tuesday, 8 December 2026',
      isoDate: '2026-12-08T12:00:00+05:30',
      time: '12:00 PM Onwards',
      venue: 'Swarg Sahyadri Farms',
      dressCode: 'Vibrant Florals & Sunshine Hues',
      icon: '🌿',
      image: '/assets/event_mehendi.jpg',
      tag: 'Henna, Laughter & Festive Beats',
      description: 'An enchanting afternoon of intricate bridal henna, rhythmic dhol beats, festive folk dance, refreshing chaat, and high tea amidst blooming florals.',
      colors: [
        { name: 'Marigold Yellow', hex: '#F59E0B' },
        { name: 'Blush Pink', hex: '#EC4899' },
        { name: 'Mint Green', hex: '#10B981' },
        { name: 'Warm Peach', hex: '#FDBA74' },
      ],
    },
    {
      id: 'sangeet',
      day: 'Day 1',
      title: 'Sangeet & Ring Ceremony',
      date: 'Tuesday, 8 December 2026',
      isoDate: '2026-12-08T19:00:00+05:30',
      time: '7:00 PM Onwards',
      venue: 'Sahyadri Mangal Karyalay',
      dressCode: 'Glamour, Shimmer & Indo-Western',
      icon: '🎶',
      image: '/assets/event_sangeet.jpg',
      tag: 'Music, Dance & Ring Exchange',
      description: 'The romantic ring exchange followed by a dazzling night of high-energy family dance battles, celebratory beats, dinner, and starlit revelry.',
      colors: [
        { name: 'Champagne Gold', hex: '#DFB141' },
        { name: 'Midnight Navy', hex: '#0F172A' },
        { name: 'Velvet Wine', hex: '#831843' },
        { name: 'Silver Shimmer', hex: '#E2E8F0' },
      ],
    },
    {
      id: 'haldi',
      day: 'Day 2',
      title: 'Haldi Ceremony',
      date: 'Wednesday, 9 December 2026',
      isoDate: '2026-12-09T12:00:00+05:30',
      time: '12:00 PM Onwards',
      venue: 'Swarg Sahyadri Farms',
      dressCode: 'Shades of Yellow & White',
      icon: '🌻',
      image: '/assets/event_haldi.jpg',
      tag: 'Turmeric Glow & Flower Petal Shower',
      description: 'The auspicious turmeric ceremony infused with playful flower petal showers, fragrant ubtan, love, and lively traditional rituals for the bride and groom.',
      colors: [
        { name: 'Turmeric Gold', hex: '#EAB308' },
        { name: 'Sunflower Yellow', hex: '#FACC15' },
        { name: 'Ivory White', hex: '#FAF5FF' },
        { name: 'Amber Glow', hex: '#D97706' },
      ],
    },
    {
      id: 'shaadi',
      day: 'Day 2',
      title: 'Shaadi & Sacred Pheras',
      date: 'Wednesday, 9 December 2026',
      isoDate: '2026-12-09T19:00:00+05:30',
      time: '7:00 PM Onwards',
      venue: 'Sahyadri Mangal Karyalay',
      dressCode: 'Royal Traditional Heritage',
      icon: '💍',
      image: '/assets/event_shaadi.jpg',
      tag: 'Grand Baraat & Saat Phere',
      description: 'The royal Baraat arrival followed by the sacred Saat Phere around the holy fire, Varmala exchange, and dinner to bless the newlyweds.',
      colors: [
        { name: 'Bridal Crimson', hex: '#991B1B' },
        { name: '24K Gold', hex: '#DFB141' },
        { name: 'Raw Silk Cream', hex: '#FEF3C7' },
        { name: 'Royal Emerald', hex: '#065F46' },
      ],
    },
  ],
  gallery: [
    { title: 'Sahyadri Mangal Karyalay', image: '/assets/venue_sahyadri.jpg', tag: 'Grand Illuminated Venue' },
    { title: 'The Sacred Saat Phere', image: '/assets/event_shaadi.jpg', tag: 'Shaadi & Mandap' },
    { title: 'Sangeet & Ring Ceremony', image: '/assets/event_sangeet.jpg', tag: 'Celebration of Music' },
    { title: 'Radiant Haldi Shower', image: '/assets/event_haldi.jpg', tag: 'Haldi Blessings' },
    { title: 'Bridal Henna & Joy', image: '/assets/event_mehendi.jpg', tag: 'Mehendi Afternoon' },
    { title: 'Little Amrit', image: '/assets/childhood_amrit.jpg', tag: 'Then & Now' },
    { title: 'Little Ankita', image: '/assets/childhood_ankita.jpg', tag: 'Then & Now' },
  ],
  hospitality: {
    airports: [
      {
        name: 'Navi Mumbai International Airport (NMI)',
        time: '1h 54 mins drive',
        badge: 'Closest Airport',
      },
      {
        name: 'Chhatrapati Shivaji Maharaj International Airport Mumbai (BOM)',
        time: '2h 30 mins drive',
        badge: 'Major International Hub',
      },
    ],
    train: {
      name: 'Kalyan Junction (KYN)',
      detail: 'Nearest major railway hub connecting Mumbai, Pune, and all interstate trains.',
    },
    stay: {
      name: 'Swarg Sahyadri Farms',
      detail: 'Reserved accommodation and check-in for wedding guests and family.',
      checkIn: 'Check-in from 11:00 AM onwards on 8th Dec.',
    },
    venue: {
      name: 'Sahyadri Mangal Karyalay',
      mapsUrl: 'https://maps.app.goo.gl/V5mNtMtpdc1T8TFp6?g_st=ic',
    },
  },
}
